// Code generated by protoc-gen-go from "fileformat.proto"
// DO NOT EDIT!

package pbf

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Blob struct {
	Raw               []byte `protobuf:"bytes,1,opt,name=raw" json:"raw,omitempty"`
	RawSize           *int32 `protobuf:"varint,2,opt,name=raw_size" json:"raw_size,omitempty"`
	ZlibData          []byte `protobuf:"bytes,3,opt,name=zlib_data" json:"zlib_data,omitempty"`
	LzmaData          []byte `protobuf:"bytes,4,opt,name=lzma_data" json:"lzma_data,omitempty"`
	OBSOLETEBzip2Data []byte `protobuf:"bytes,5,opt,name=OBSOLETE_bzip2_data" json:"OBSOLETE_bzip2_data,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (this *Blob) Reset()         { *this = Blob{} }
func (this *Blob) String() string { return proto.CompactTextString(this) }

type BlobHeader struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Indexdata        []byte  `protobuf:"bytes,2,opt,name=indexdata" json:"indexdata,omitempty"`
	Datasize         *int32  `protobuf:"varint,3,req,name=datasize" json:"datasize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BlobHeader) Reset()         { *this = BlobHeader{} }
func (this *BlobHeader) String() string { return proto.CompactTextString(this) }

func init() {
}
